### ISSUE TITLE
Feature Request: Support Fenix 3HR watch

### ISSUE THREAD

**Issue by fds2610** [cedric-dufour/connectiq-app-glidersk#2]
Hi Cedric,
as my old Fenix 3 has a 218x218 display it currently not seems to be supported. Is there a chance to make it run? I could add my 2 cents in coding / configuring / testing if needed... how can I contribute?
rgds, Felix

**Comment by cedric-dufour** [comment]
Hello,
Fenix 3 don't have enough RAM: https://developer.garmin.com/connect-iq/reference-guides/devices-reference/#f%C4%93nix%C2%AE3hr
Sorry
